### ISSUE TITLE
请问有数据集可以提供吗

### ISSUE THREAD

**Issue by cainiaozp** [iYuqinL/tumblerElf#1]
请问有数据集可以提供吗

**Comment by iYuqinL** [comment]
@cainiaozp 你好，由于我的电脑已经换过了，也不在实验室，暂时找不到数据了。
不过我们的数据就是很小的一个自己标注的数据集(~1000 images)，图片都是网上爬取的然后标注的。
而且由于我们的数据太少，实际上这个模型的泛化性也不够好；所以可能寻找/制作更加符合你的应用领域的数据是更好的。

**Comment by cainiaozp** [comment]
好的，好的，谢谢------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年8月23日(星期一) 中午11:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Yusnows/tumblerElf] 请问有数据集可以提供吗 (#1)
